### ISSUE TITLE
Config file for tv_grab_zz_sdjson

### ISSUE THREAD

**Issue by jangeador** [kens13/EPG#1]
Hello. Can you share the SD lineups that you use to generate this guide? I have a subscription to SD, but I cannot find the correct lineups to get the most coverage. I use tv_grab_sd_json as well.

**Comment by kens13** [comment]
[tv_grab_zz_sdjson.conf-copynouserpw.txt](https://github.com/kens13/EPG/files/3437397/tv_grab_zz_sdjson.conf-copynouserpw.txt)

**Comment by kens13** [comment]
dont know if u still need this, ...but here you go.
kens

**Comment by jangeador** [comment]
Thanks. Much appreciated.
